@startuml delete products
' === Style Tweaks ===

skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  SequenceStereotype {
    Font {
      Size 10
      Style plain
    }
  }
}

' === Actors / Participants
actor "User" as user
participant "ProductCatalogue\n:MainMenu" as menu <<form>>
participant "ProductViewer\n:ViewProuductForm" as viewProduct <<form>>
participant "OptionPane\n:deleteForm" as optionForm <<form>>
participant "dataStore\n:ProductCollectionsDAO" as dataStore <<data store>>

' === Messages ===
user -> menu : click "View Products"
menu++
menu -> viewProduct : ProductViewer()
viewProduct++

viewProduct -> dataStore : getProducts()
dataStore++
return products

viewProduct -> viewProduct : updateItems(products)

user -> viewProduct : select product
user -> viewProduct : click "Delete"
viewProduct -> optionForm : showConfirmDialog()
user -> optionForm : click "Yes"
optionForm --> viewProduct
destroy optionForm

viewProduct -> dataStore : removeProduct(selectedProduct)
dataStore++
dataStore--
viewProduct -> viewProduct : updateItems(products)

user -> viewProduct : click "Close"
viewProduct --> menu
destroy viewProduct

@enduml