/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package etail;

import gui.MainMenu;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        //System.out.println(new App().getGreeting());
    }
}
